### PR TITLE
[sc-9148] Minor idiomatic Swift updates to Plugin.swift

### PR DESCRIPTION
**Pull request by jrtibbetts**
[[sc-9148] [iOS Capacitor] Use more idiomatic Swift in Plugin.swift](https://app.shortcut.com/radarlabs/story/9148/ios-capacitor-clean-up-plugin-swift)

@jsani-radar [pointed out](https://github.com/radarlabs/capacitor-radar/pull/26#r817036564) in #26 that some statements like `user?.dictionaryValue() ?? []` were using different types (`Dictionary` and `Array`) on both sides of the `??` operator. It turns out that we can avoid the issue altogether by using `guard let`s.

This also replaces some case-sensitive comparisons with cleaner checks, and uses a more Swift-like shorthand for getting raw values from `enum`s.

### CODE REVIEW

**Comment by jsani-radar** [comment]
can we merge / rebase this to get a cleaner diff since https://github.com/radarlabs/capacitor-radar/pull/26 is now in?

**Comment by jrtibbetts** [comment]
@jsani-radar, this already has the #26 changes. I can merge it again after #33 has been merged.

**Review by phil-brown — APPROVED** [review]

**Comment by jrtibbetts** [comment]
#33 has been merged, so this one is no longer marked as a **draft**.

**Comment by nickpatrick** [comment]
Going to take this out in a subsequent release so as not to complicate this release

**Pull request closed without merging**
